package com.springboot.app2.wiki.testing;

/**
 * MOCK
 * Mocks are used to create fully mock or dummy objects. It is mainly used in large test suites.
 * When using mock objects, the default behavior of methods (when not stubbed) is do nothing (performs nothing.)
 *
 * SPY
 * Spies are used for creating partial or half mock objects. Like mock, spies are also used in large test suites.
 * When using spy objects, the default behavior of the methods (when not stubbed) is the real method behavior.
 *
 *
 *
 * STUB
 * The data source of stubs is hardcoded. It is usually tightly coupled to the test suite.
 * Stubs are usually handwritten, and some are generated by tools.
 * Stubs are mainly used for simple test suites.
 * Stubs do not have a GUI.
 *
 * MOCK
 * Data on mocks is set up by the tests.
 * Mocks are usually created by using the third-party library such as Mockito, JMock, and WireMock.
 * Mocks are mainly used for large test suites.
 * Mocks have a GUI.
 *
 */
public class TestingMockVsSpyVsStub {
}
